apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postpilot-application-secrets
  namespace: postpilot
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  provider: aws
  secretObjects:
    - secretName: postpilot-secrets
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: NEXTAUTH_SECRET
          key: NEXTAUTH_SECRET
        - objectName: NEXTAUTH_URL
          key: NEXTAUTH_URL
        - objectName: POSTPILOT_DEBUG_DEMO
          key: POSTPILOT_DEBUG_DEMO
  parameters:
    region: eu-west-1
    usePodIdentity: "true"
    objects: |
      - objectName: "postpilot/application"
        objectType: "secretsmanager"
        jmesPath:
          - path: DATABASE_URL
            objectAlias: DATABASE_URL
          - path: NEXTAUTH_SECRET
            objectAlias: NEXTAUTH_SECRET
          - path: NEXTAUTH_URL
            objectAlias: NEXTAUTH_URL
          - path: POSTPILOT_DEBUG_DEMO
            objectAlias: POSTPILOT_DEBUG_DEMO
