packages:
  - "site"

allowBuilds:
  '@heroui/shared-utils': false
  esbuild: true
  sharp: false
  unrs-resolver: false
overrides:
  sharp: 0.35.0
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
