import { AlertTriangle, ArrowLeft, ExternalLink, FileClock, ReceiptText } from "lucide-react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";

import { ClientPurchaseOrderActions } from "@/components/client-purchase-order-actions";
import { ClientPurchaseOrderForm } from "@/components/client-purchase-order-form";
import { getActiveOrganizationContext } from "@/lib/organizations";
import { can } from "@/lib/permissions";
import { listCrmCompanyOptions } from "@/server/data/crm";
import { listEpisodes } from "@/server/data/episodes";
import { getActiveClientPurchaseOrderDetail } from "@/server/data/client-purchase-orders";
import { listShowOptions } from "@/server/data/shows";

export default async function ClientPurchaseOrderDetailPage({ params }: { params: Promise<{ clientPurchaseOrderId: string }> }) {
  if (!(await can("manage_budget"))) redirect("/");
  const context = await getActiveOrganizationContext();
  if (!context?.organization) redirect("/");
  const { clientPurchaseOrderId } = await params;
  const [order, companies, shows, episodes, mayApprove] = await Promise.all([getActiveClientPurchaseOrderDetail(clientPurchaseOrderId), listCrmCompanyOptions(context.organization.organizationId), listShowOptions(context.organization.organizationId), listEpisodes(context.organization.organizationId), can("approve_budget_overruns")]);
  if (!order) notFound();
  const expiry = expiryState(order.expiryDate, order.status); const isOverAuthorised = order.remainingAmount < 0; const isExhausted = order.status === "active" && order.remainingAmount === 0;
  const formOptions = { currency: context.organization.currency, clients: companies.filter((company) => company.type !== "vendor"), shows, episodes: episodes.map((episode) => ({ id: episode.id, showId: episode.showId, showTitle: episode.showTitle, number: episode.number, title: episode.title })) };
  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link href="/budget/client-purchase-orders" className="inline-flex items-center gap-1 text-xs font-semibold text-[#58756b]"><ArrowLeft size={14}/> Client POs</Link><p className="mt-4 text-xs font-medium uppercase tracking-[.12em] text-[#7c827f]">{statusLabel(order.status)} client billing authorisation</p><h1 className="mt-2 text-[27px] font-semibold tracking-[-.045em] text-[#202524]">{order.poNumber}</h1><p className="mt-1 text-sm text-[#747977]">{order.clientName ?? "Client"} · {order.showTitle ?? "All shows"}{order.episodeTitle ? ` · E${String(order.episodeNumber ?? 0).padStart(2, "0")} ${order.episodeTitle}` : ""}</p></div><div className="flex flex-wrap items-center gap-2">{order.status === "draft" && <ClientPurchaseOrderForm {...formOptions} purchaseOrder={order}/>}<ClientPurchaseOrderActions purchaseOrderId={order.id} status={order.status} mayApprove={mayApprove}/></div></header>
    {(expiry || isOverAuthorised || isExhausted) && <section role="alert" className="flex gap-3 rounded-xl border border-[#efd8cf] bg-[#fff7f3] px-4 py-3 text-sm text-[#8b4f38]"><AlertTriangle size={17} className="mt-0.5 shrink-0"/><div><p className="font-semibold">Client PO needs attention</p><p className="mt-1 text-xs leading-5">{[isOverAuthorised ? `Committed billing exceeds the authorised amount by ${money(Math.abs(order.remainingAmount), order.currency)}.` : null, isExhausted ? "All authorised value is committed; no further change work can use this PO." : null, expiry?.message].filter(Boolean).join(" ")}</p></div></section>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Authorised" value={money(order.authorisedAmount, order.currency)}/><Metric label="Committed to bill" value={money(order.committedToBillAmount, order.currency)}/><Metric label="Invoiced" value={money(order.invoicedAmount, order.currency)}/><Metric label="Remaining" value={money(order.remainingAmount, order.currency)} warning={isOverAuthorised}/><Metric label="Variance" value={`${order.varianceAmount > 0 ? "+" : ""}${money(order.varianceAmount, order.currency)}`} warning={order.varianceAmount > 0}/></section>
    <section className="panel grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_260px]"><div><h2 className="text-sm font-semibold text-[#353b39]">Client authorisation scope</h2>{order.notes ? <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#5f6964]">{order.notes}</p> : <p className="mt-2 text-sm text-[#858a87]">No internal authorisation note.</p>}{order.externalDocumentUrl && <a className="mt-4 inline-flex items-center gap-1.5 text-sm font-semibold text-[#58756b]" href={order.externalDocumentUrl} target="_blank" rel="noreferrer">Open supporting document <ExternalLink size={14}/></a>}</div><dl className="grid gap-3 text-sm"><Fact label="Status" value={statusLabel(order.status)}/><Fact label="Issue date" value={date(order.issueDate)}/><Fact label="Expiry date" value={date(order.expiryDate)}/><Fact label="Currency" value={order.currency}/></dl></section>
    <section className="panel overflow-hidden"><div className="flex items-center gap-2 border-b border-[#ebeae6] px-5 py-4"><ReceiptText size={16} className="text-[#59756c]"/><div><h2 className="text-sm font-semibold text-[#353b39]">Allocation ledger</h2><p className="mt-1 text-xs text-[#737b77]">Billable commitments and issued client invoices remain separate. Allocation controls arrive with billing integration.</p></div></div>{!order.allocations.length ? <Empty text="No billable, invoice, or change-order entries have been allocated to this client PO yet."/> : <div className="divide-y divide-[#efeeea]">{order.allocations.map((allocation) => <div key={allocation.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[130px_minmax(0,1fr)_130px_130px] sm:items-center"><div><p className="text-sm font-medium text-[#3d4642]">{allocationLabel(allocation.allocationType)}</p><p className="mt-1 text-xs text-[#858a87]">{date(allocation.allocationDate)}</p></div><div className="min-w-0"><p className="truncate text-sm text-[#525c57]">{allocation.description ?? "No description"}</p><p className="mt-1 truncate text-xs text-[#858a87]">{allocation.reference ?? allocation.changeOrderReference ?? "No reference"}</p>{allocation.overrunAuthorised && <p className="mt-1 text-xs font-semibold text-[#9a613f]">Overrun approved</p>}</div><p className="text-sm font-semibold text-[#4d5752]">{money(Number(allocation.amount), order.currency)}</p><p className="text-xs text-[#77807b]">{allocation.createdAt ? `Recorded ${date(allocation.createdAt)}` : "Recorded"}</p></div>)}</div>}</section>
    <section className="panel overflow-hidden"><div className="flex items-center gap-2 border-b border-[#ebeae6] px-5 py-4"><FileClock size={16} className="text-[#59756c]"/><div><h2 className="text-sm font-semibold text-[#353b39]">Activity</h2><p className="mt-1 text-xs text-[#737b77]">Client PO lifecycle and billing-authorisation events.</p></div></div>{!order.activity.length ? <Empty text="No activity has been recorded for this client PO."/> : <div className="divide-y divide-[#efeeea]">{order.activity.map((event) => <div key={event.id} className="flex flex-col gap-1 px-5 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-medium text-[#4d5752]">{activityLabel(event.action)}</p><p className="mt-1 text-xs text-[#858a87]">{event.actorName ?? "System"}</p></div><p className="text-xs text-[#77807b]">{date(event.createdAt)}</p></div>)}</div>}</section>
  </div>;
}

function Metric({ label, value, warning = false }: { label: string; value: string; warning?: boolean }) { return <div className="panel p-4"><p className={`text-xs font-semibold uppercase tracking-[.08em] ${warning ? "text-[#a35e41]" : "text-[#76807b]"}`}>{label}</p><p className={`mt-3 text-xl font-semibold tracking-[-.035em] ${warning ? "text-[#a35e41]" : "text-[#343d39]"}`}>{value}</p></div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3 border-b border-[#efeeea] pb-2 last:border-0"><dt className="text-[#858a87]">{label}</dt><dd className="text-right font-medium capitalize text-[#4d5752]">{value}</dd></div>; }
function Empty({ text }: { text: string }) { return <p className="px-5 py-12 text-center text-sm text-[#858a87]">{text}</p>; }
function money(value: number, currency: string) { try { return new Intl.NumberFormat("en-GB", { style: "currency", currency, minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); } catch { return `${currency} ${value.toFixed(2)}`; } }
function date(value: string | Date | null | undefined) { return value ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "—"; }
function statusLabel(status: string) { return status.replaceAll("_", " "); }
function allocationLabel(type: string) { return type === "billable" ? "Billable" : type === "client_invoice" ? "Client invoice" : "Change order"; }
function activityLabel(action: string) { return action.replace(/^client_purchase_order\./, "Client PO ").replaceAll("_", " "); }
function expiryState(value: string | Date | null, status: string) { if (!value || status !== "active") return null; const expiry = new Date(value); const today = new Date(); expiry.setHours(0, 0, 0, 0); today.setHours(0, 0, 0, 0); const days = Math.round((expiry.getTime() - today.getTime()) / 86_400_000); if (days < 0) return { message: `This client PO expired ${Math.abs(days)} day${Math.abs(days) === 1 ? "" : "s"} ago.` }; if (days <= 14) return { message: `This client PO expires in ${days} day${days === 1 ? "" : "s"}.` }; return null; }
