import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { reviewCuts, reviewNotes } from "@/lib/db/schema";
import { getActiveOrganizationContext } from "@/lib/organizations";
import { isDebugDemoMode } from "@/lib/runtime";
import { can, getCurrentPerson, isExternalReviewerRole } from "@/lib/permissions";
import { writeAuditEvent } from "@/lib/audit";
export async function PATCH(_request: Request, { params }: { params: Promise<{ noteId: string }> }) { if (!(await can("update_notes"))) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); if (isDebugDemoMode) return NextResponse.json({ ok: true, debug: true }); const { noteId } = await params; const context = await getActiveOrganizationContext(); if (!context?.organization) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const person = await getCurrentPerson(); if (isExternalReviewerRole(person?.role)) return NextResponse.json({ error: "External reviewers can request changes, but cannot resolve internal notes." }, { status: 403 }); const db = getDb(); const [note] = await db.select({ organizationId: reviewCuts.organizationId }).from(reviewNotes).innerJoin(reviewCuts, eq(reviewNotes.reviewCutId, reviewCuts.id)).where(and(eq(reviewNotes.id, noteId), eq(reviewNotes.organizationId, context.organization.organizationId), eq(reviewCuts.organizationId, context.organization.organizationId))).limit(1); if (note?.organizationId !== context.organization.organizationId) return NextResponse.json({ error: "Note not found." }, { status: 404 }); await db.update(reviewNotes).set({ status: "addressed", addressedAt: new Date(), updatedAt: new Date() }).where(and(eq(reviewNotes.id, noteId), eq(reviewNotes.organizationId, context.organization.organizationId))); await writeAuditEvent({ organizationId: context.organization.organizationId, actorUserId: context.userId, action: "review_note.addressed", entityType: "review_note", entityId: noteId }); return NextResponse.json({ ok: true }); }
