import Link from "next/link";
import { Building2, ContactRound, ReceiptText, Tags } from "lucide-react";
import { redirect } from "next/navigation";

import { getActiveOrganizationContext } from "@/lib/organizations";
import { can } from "@/lib/permissions";
import { getCrmData } from "@/server/data/crm";

export default async function CrmPage() {
  if (!(await can("manage_shows")) && !(await can("manage_budget"))) redirect("/");
  const context = await getActiveOrganizationContext();
  const data = context?.organization ? await getCrmData(context.organization.organizationId) : { companies: [], contacts: [], purchaseOrders: [], rateCards: [], vendorInvoices: [], workOrders: [] };
  const openPurchaseOrders = data.purchaseOrders.filter((po) => po.status === "open");
  return <div className="space-y-5">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-medium uppercase tracking-[.12em] text-[#7c827f]">Commercial contacts · {context?.organization?.organizationName ?? "Workspace"}</p><h1 className="mt-2 text-[27px] font-semibold tracking-[-.045em] text-[#202524]">Clients & vendors</h1><p className="mt-1 text-sm text-[#747977]">Account contacts, POs, supplier invoices, and rate-card context for post production.</p></div>{await can("manage_budget") && <Link href="/crm/purchase-orders" className="rounded-lg bg-[#263130] px-3 py-2 text-xs font-semibold text-white">Purchase orders</Link>}</header>
    <section className="grid gap-3 sm:grid-cols-4"><Metric icon={<Building2 size={16}/>} label="Accounts" value={data.companies.length}/><Metric icon={<ContactRound size={16}/>} label="Contacts" value={data.contacts.length}/><Metric icon={<ReceiptText size={16}/>} label="Open POs" value={openPurchaseOrders.length}/><Metric icon={<Tags size={16}/>} label="Rate cards" value={data.rateCards.length}/></section>
    <section className="grid gap-4 xl:grid-cols-2"><AccountList title="Client accounts" empty="No client accounts yet." companies={data.companies.filter((company) => company.type !== "vendor")} purchaseOrders={data.purchaseOrders}/><AccountList title="Vendor accounts" empty="No vendor accounts yet." companies={data.companies.filter((company) => company.type === "vendor")} purchaseOrders={data.purchaseOrders} /></section>
    <section className="panel overflow-hidden"><div className="border-b px-5 py-4 text-sm font-semibold">Operational contacts</div>{data.contacts.map((contact) => <div key={contact.id} className="flex flex-col justify-between gap-2 border-b px-5 py-3 text-sm sm:flex-row sm:items-center"><div><p className="font-medium text-[#3d4642]">{contact.name}<span className="ml-2 rounded bg-[#edf1ee] px-1.5 py-0.5 text-[10px] font-semibold text-[#557269]">{contact.contactType.replaceAll("_", " ")}</span></p><p className="mt-1 text-xs text-[#858a87]">{contact.title ?? "Title not set"} · {contact.companyName}</p></div><p className="text-xs text-[#68716d]">{contact.email ?? "No email"}{contact.phone ? ` · ${contact.phone}` : ""}</p></div>)}{!data.contacts.length && <p className="px-5 py-8 text-sm text-[#858a87]">No operational contacts yet.</p>}</section>
  </div>;
}

function AccountList({ title, empty, companies, purchaseOrders }: { title: string; empty: string; companies: Array<{ id: string; name: string; type: string; accountStatus: string; currency: string; paymentTermsDays: number | null; serviceCategory: string | null; isPreferredSupplier: boolean }>; purchaseOrders: Array<{ companyId: string; status: string; approvedAmount: string | number | null; consumedAmount: string | number }> }) {
  return <section className="panel overflow-hidden"><div className="border-b px-5 py-3 text-sm font-semibold">{title}</div>{companies.map((company) => { const pos = purchaseOrders.filter((po) => po.companyId === company.id && po.status === "open"); const remaining = pos.reduce((total, po) => total + Number(po.approvedAmount ?? 0) - Number(po.consumedAmount ?? 0), 0); return <Link key={company.id} href={`/crm/accounts/${company.id}`} className="block border-b px-5 py-3 hover:bg-[#fafbf9]"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-[#3d4642]">{company.name}{company.isPreferredSupplier && <span className="ml-2 rounded bg-[#e5eee8] px-1.5 py-0.5 text-[10px] text-[#477263]">Preferred</span>}</p><p className="mt-1 truncate text-xs text-[#818784]">{company.serviceCategory ?? company.type.replaceAll("_", " ")} · {company.paymentTermsDays ? `Net ${company.paymentTermsDays}` : "Terms not set"}</p></div><p className="shrink-0 text-right text-xs text-[#68716d]">{pos.length} open PO{pos.length === 1 ? "" : "s"}<br/>{company.currency} {remaining.toFixed(2)} left</p></div></Link>; })}{!companies.length && <p className="px-5 py-8 text-sm text-[#858a87]">{empty}</p>}</section>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="panel flex items-center gap-3 p-4"><span className="rounded-lg bg-[#eaf0ec] p-2 text-[#58736a]">{icon}</span><div><p className="text-lg font-semibold text-[#303734]">{value}</p><p className="text-xs text-[#7c827f]">{label}</p></div></div>; }
