import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { getActiveOrganizationContext } from "@/lib/organizations";
import { can } from "@/lib/permissions";
import { getCrmAccount } from "@/server/data/crm";

export default async function CrmAccountPage({ params }: { params: Promise<{ companyId: string }> }) { if (!(await can("manage_shows")) && !(await can("manage_budget"))) redirect("/"); const context = await getActiveOrganizationContext(); if (!context?.organization) notFound(); const { companyId } = await params; const data = await getCrmAccount(context.organization.organizationId, companyId); if (!data) notFound(); const { company } = data; const open = data.purchaseOrders.filter((po) => po.status === "open"); const remaining = open.reduce((total, po) => total + Number(po.amount ?? 0) - Number(po.consumedAmount ?? 0), 0); return <div className="space-y-5"><Link href="/crm" className="flex items-center gap-1 text-xs font-medium text-[#617b75]"><ArrowLeft size={14}/> Clients & vendors</Link><header className="panel p-5"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[#7c827f]">{company.type.replaceAll("_", " ")}</p><h1 className="mt-1 text-[27px] font-semibold tracking-[-.045em] text-[#202524]">{company.name}</h1><p className="mt-1 text-sm text-[#747977]">{company.address ?? "Address not set"} · {company.paymentTermsDays ? `Net ${company.paymentTermsDays}` : "Terms not set"} · {company.currency}</p></header><section className="grid gap-3 sm:grid-cols-3"><Metric label="Open POs" value={String(open.length)}/><Metric label="Available PO balance" value={`${company.currency} ${remaining.toFixed(2)}`}/><Metric label="Budget exposure" value={`${company.currency} ${data.budgetExposure.toFixed(2)}`}/></section><section className="grid gap-4 lg:grid-cols-2"><Rows title="Contacts" empty="No contacts." rows={data.contacts.map((contact) => ({ id: contact.id, primary: contact.name, secondary: `${contact.title ?? "No title"}${contact.email ? ` · ${contact.email}` : ""}` }))}/><Rows title="Purchase orders" empty="No POs." rows={data.purchaseOrders.map((po) => ({ id: po.id, primary: po.poNumber, secondary: `${po.kind.replaceAll("_", " ")} · ${po.currency} ${(Number(po.amount ?? 0)-Number(po.consumedAmount ?? 0)).toFixed(2)} remaining` }))}/></section>{company.type === "vendor" ? <section className="grid gap-4 lg:grid-cols-2"><Rows title="Active work orders" empty="No vendor work orders." rows={data.workOrders.filter((item) => !["complete", "cancelled"].includes(item.status)).map((item) => ({ id: item.id, primary: item.title, secondary: `E${String(item.episodeNumber).padStart(2, "0")} ${item.episodeTitle} · ${item.status}` }))}/><Rows title="Vendor invoices" empty="No vendor invoices." rows={data.invoices.map((item) => ({ id: item.id, primary: item.invoiceNumber, secondary: `${item.currency} ${Number(item.amount).toFixed(2)} · ${item.status}` }))}/></section> : <Rows title="Shows" empty="No related shows." rows={data.shows.map((show) => ({ id: show.id, primary: show.title, secondary: `${show.code}${show.network ? ` · ${show.network}` : ""}` }))}/>}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="panel p-4"><p className="text-xs text-[#7d837f]">{label}</p><p className="mt-1 text-lg font-semibold text-[#303734]">{value}</p></div>; }
function Rows({ title, empty, rows }: { title: string; empty: string; rows: Array<{ id: string; primary: string; secondary: string }> }) { return <section className="panel overflow-hidden"><div className="border-b px-5 py-3 text-sm font-semibold">{title}</div>{rows.map((row) => <div key={row.id} className="border-b px-5 py-3"><p className="text-sm font-medium text-[#48524d]">{row.primary}</p><p className="mt-1 text-xs text-[#818783]">{row.secondary}</p></div>)}{!rows.length && <p className="px-5 py-8 text-sm text-[#858a87]">{empty}</p>}</section>; }
