"use client";
import { Button } from "@heroui/react";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function ActualTimeDialog({ booking }: { booking: { id: string; startsAt: Date; endsAt: Date; title: string } }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [start, setStart] = useState(input(booking.startsAt)); const [end, setEnd] = useState(input(booking.endsAt)); const [overtime, setOvertime] = useState(0); const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async () => { setSaving(true); setMessage(""); const response = await fetch(`/api/bookings/${booking.id}/time-submissions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ actualStartsAt: new Date(start).toISOString(), actualEndsAt: new Date(end).toISOString(), overtimeMinutes: overtime, note: note || null }) }); const body = await response.json(); setSaving(false); if (!response.ok) return setMessage(body.error ?? "Could not save actual time."); setOpen(false); router.refresh(); };
  return <><Button size="sm" variant="tertiary" onPress={() => setOpen(true)} className="border border-[#dfe1dd] bg-white text-[#54605b]">Confirm actual time</Button>{open && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-[#202725]/25 p-4"><div className="w-full max-w-md rounded-xl border border-[#e2e3de] bg-[#fafbf9] p-6 shadow-2xl"><h2 className="text-lg font-semibold text-[#2d3431]">Confirm actual time</h2><p className="mt-1 text-sm text-[#767c78]">{booking.title}. Confirmed time updates cost and billing immediately.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Actual start<input type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} className="mt-1.5 h-10 w-full rounded-md border border-[#dedfda] bg-[#fafbf9] px-3 text-sm" /></label><label className="text-xs font-medium">Actual end<input type="datetime-local" value={end} onChange={(e) => setEnd(e.target.value)} className="mt-1.5 h-10 w-full rounded-md border border-[#dedfda] bg-[#fafbf9] px-3 text-sm" /></label></div><label className="mt-3 block text-xs font-medium">Overtime minutes<input type="number" min="0" value={overtime} onChange={(e) => setOvertime(Number(e.target.value))} className="mt-1.5 h-10 w-full rounded-md border border-[#dedfda] bg-[#fafbf9] px-3 text-sm" /></label><label className="mt-3 block text-xs font-medium">Handover / time note<textarea rows={2} value={note} onChange={(e) => setNote(e.target.value)} className="mt-1.5 w-full rounded-md border border-[#dedfda] bg-[#fafbf9] p-3 text-sm" /></label>{message && <p role="alert" className="mt-3 text-xs text-[#a35e41]">{message}</p>}<div className="mt-4 flex justify-end gap-2"><Button variant="tertiary" isDisabled={saving} onPress={() => setOpen(false)}>Cancel</Button><Button variant="primary" isDisabled={saving} onPress={submit} className="bg-[#263130] text-white">{saving ? "Saving…" : "Confirm time"}</Button></div></div></div>}</>;
}
function input(date: Date) { const pad = (value: number) => String(value).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
