"use client";

import { Button } from "@heroui/react";
import { CopyPlus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import type { BookingResources } from "@/components/booking-form-dialog";

export function CopyEpisodeBookingsDialog({ resources, initialStart }: { resources: BookingResources; initialStart: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [sourceEpisodeId, setSourceEpisodeId] = useState(""); const [targetEpisodeId, setTargetEpisodeId] = useState(""); const [startsOn, setStartsOn] = useState(initialStart.slice(0, 10)); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async () => { setMessage(""); if (!sourceEpisodeId || !targetEpisodeId || !startsOn) return setMessage("Choose a source episode, target episode, and start date."); setSaving(true); const response = await fetch("/api/bookings/copy-episode", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceEpisodeId, targetEpisodeId, startsOn: new Date(`${startsOn}T09:00`).toISOString() }) }); const body = await response.json(); setSaving(false); if (!response.ok) return setMessage(body.error ?? "Could not copy the sequence."); setOpen(false); router.refresh(); };
  return <><Button variant="tertiary" onPress={() => setOpen(true)} className="border border-[#dfe1dd] bg-white text-[#54605b]"><CopyPlus size={16} /> Copy episode sequence</Button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#202725]/25 p-4" role="dialog" aria-modal="true" aria-label="Copy episode booking sequence"><div className="w-full max-w-lg rounded-xl border border-[#e2e3de] bg-[#fafbf9] p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 className="text-lg font-semibold text-[#2d3431]">Copy episode booking sequence</h2><p className="mt-1 text-sm text-[#767c78]">Use a completed episode as a reusable editorial, finishing, mix, and QC booking template.</p></div><Button isIconOnly variant="tertiary" onPress={() => setOpen(false)} aria-label="Close"><X size={18} /></Button></div><div className="mt-5 space-y-4"><Field label="Template episode"><select value={sourceEpisodeId} onChange={(event) => setSourceEpisodeId(event.target.value)}><option value="">Choose source episode</option>{resources.episodes.map((episode) => <option key={episode.id} value={episode.id}>{episode.label}</option>)}</select></Field><Field label="Target episode"><select value={targetEpisodeId} onChange={(event) => setTargetEpisodeId(event.target.value)}><option value="">Choose target episode</option>{resources.episodes.map((episode) => <option key={episode.id} value={episode.id}>{episode.label}</option>)}</select></Field><Field label="First client booking date"><input type="date" value={startsOn} onChange={(event) => setStartsOn(event.target.value)} /></Field><p className="rounded-lg border border-[#e1e5e1] bg-[#f2f6f3] p-3 text-xs text-[#5e7068]">Copies all source bookings at their relative timing, including room, person, and operational buffers. New bookings are tentative and checked for conflicts before creation.</p>{message && <p role="alert" className="text-xs text-[#a35e41]">{message}</p>}<div className="flex justify-end gap-2 border-t border-[#ecebe7] pt-4"><Button variant="tertiary" onPress={() => setOpen(false)}>Cancel</Button><Button variant="primary" isDisabled={saving} onPress={submit} className="bg-[#263130] text-white">{saving ? "Copying…" : "Copy sequence"}</Button></div></div></div></div>}</>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-medium text-[#535b57]">{label}<span className="mt-1.5 block [&_input]:h-10 [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-[#dedfda] [&_input]:bg-[#fafbf9] [&_input]:px-3 [&_input]:text-sm [&_select]:h-10 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-[#dedfda] [&_select]:bg-[#fafbf9] [&_select]:px-2 [&_select]:text-sm">{children}</span></label>; }
