"use client";

import Link from "next/link";
import { Search } from "lucide-react";
import { useMemo, useState } from "react";

type AccountRow = { id: string; name: string; type: string; accountStatus: string; bookingClearance: string; ownerName: string | null; activeShowCount: number; contactCount: number; nextAction: string | null; nextActionDueAt: string | null; openPurchaseOrderCount: number; remainingAuthorisedSpend: number; currency: string };
const filters = ["all", "client", "production_company", "network", "studio", "vendor", "on_hold"] as const;

export function CrmAccountDirectory({ accounts, showFinancials }: { accounts: AccountRow[]; showFinancials: boolean }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<(typeof filters)[number]>("all");
  const visible = useMemo(() => accounts.filter((account) => (filter === "all" || filter === "on_hold" ? filter === "on_hold" ? account.accountStatus === "on_hold" : true : account.type === filter) && `${account.name} ${account.type} ${account.ownerName ?? ""} ${account.nextAction ?? ""}`.toLowerCase().includes(query.toLowerCase())), [accounts, filter, query]);
  return <section className="panel overflow-hidden"><div className="border-b border-[#ebeae6] px-5 py-4"><div className="flex flex-col justify-between gap-3 lg:flex-row lg:items-center"><div><h2 className="text-sm font-semibold text-[#343b38]">Accounts</h2><p className="mt-1 text-xs text-[#858a87]">Find the right external partner, relationship owner, and booking clearance.</p></div><label className="flex h-9 min-w-0 items-center gap-2 rounded-md border border-[#dedfda] bg-white px-3 text-[#7d837f] lg:w-80"><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search accounts, owners, actions…" className="min-w-0 flex-1 bg-transparent text-sm text-[#3d4642] outline-none" /></label></div><div className="mt-3 flex flex-wrap gap-2">{filters.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${filter === item ? "bg-[#263130] text-white" : "bg-[#f0f2ef] text-[#65706a] hover:bg-[#e5e9e5]"}`}>{label(item)}</button>)}</div></div><div className="hidden grid-cols-[minmax(180px,1.25fr)_130px_90px_minmax(170px,1fr)_150px] gap-3 border-b border-[#ebeae6] bg-[#fafaf8] px-5 py-3 text-[10px] font-semibold uppercase tracking-[.08em] text-[#7e837f] md:grid"><span>Account</span><span>Owner</span><span>Shows</span><span>Booking clearance</span><span>{showFinancials ? "Open PO balance" : "Next action"}</span></div><div className="divide-y divide-[#efeeea]">{visible.map((account) => <Link key={account.id} href={`/crm/accounts/${account.id}`} className="grid gap-2 px-5 py-4 hover:bg-[#fafbf9] md:grid-cols-[minmax(180px,1.25fr)_130px_90px_minmax(170px,1fr)_150px] md:items-center md:gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold text-[#3d4642]">{account.name}</p><Status status={account.accountStatus}/></div><p className="mt-1 text-xs capitalize text-[#7d837f]">{account.type.replaceAll("_", " ")} · {account.contactCount} contacts</p></div><p className="text-xs text-[#66716c]"><span className="md:hidden">Owner · </span>{account.ownerName ?? "Unassigned"}</p><p className="text-xs text-[#66716c]"><span className="md:hidden">Shows · </span>{account.activeShowCount} active</p><div><Clearance value={account.bookingClearance}/></div><p className="text-xs text-[#66716c]">{showFinancials ? `${account.openPurchaseOrderCount} open · ${money(account.remainingAuthorisedSpend, account.currency)} left` : account.nextAction ? `${account.nextAction}${account.nextActionDueAt ? ` · ${formatDate(account.nextActionDueAt)}` : ""}` : "No follow-up set"}</p></Link>)}{!visible.length && <p className="px-5 py-10 text-center text-sm text-[#858a87]">No accounts match this view.</p>}</div></section>;
}

export function Clearance({ value }: { value: string }) { const styles: Record<string, string> = { clear: "bg-[#e5eee8] text-[#477263]", po_required: "bg-[#f6ebde] text-[#9a613f]", finance_approval: "bg-[#f4e5df] text-[#9a5b3f]", on_hold: "bg-[#f1ece9] text-[#8c5f51]" }; return <span className={`inline-flex rounded px-2 py-1 text-[10px] font-semibold ${styles[value] ?? styles.clear}`}>{label(value)}</span>; }
function Status({ status }: { status: string }) { return <span className={`rounded px-1.5 py-0.5 text-[10px] font-semibold ${status === "active" ? "bg-[#e5eee8] text-[#477263]" : "bg-[#f1f0ed] text-[#707672]"}`}>{label(status)}</span>; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase()); }
function money(value: number, currency: string) { try { return new Intl.NumberFormat("en-GB", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); } catch { return `${currency} ${value.toFixed(0)}`; } }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short" }).format(new Date(value)); }
