"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@heroui/react";
import { Plus, UserPlus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";

const accountSchema = z.object({ name: z.string().trim().min(2, "Enter an account name."), type: z.enum(["client", "vendor", "network", "studio", "production_company"]), currency: z.string().trim().length(3, "Use a three-letter currency."), paymentTermsDays: z.coerce.number().int().min(0).max(365).optional(), financeEmail: z.string().trim().email("Enter a valid email.").or(z.literal("")), bookingClearance: z.enum(["clear", "po_required", "finance_approval", "on_hold"]) });
const contactSchema = z.object({ companyId: z.string().uuid("Choose an account."), name: z.string().trim().min(2, "Enter a contact name."), title: z.string().trim().max(160), email: z.string().trim().email("Enter a valid email.").or(z.literal("")), phone: z.string().trim().max(80), contactType: z.enum(["general", "creative_approval", "technical_delivery", "finance", "legal", "client_review"]), isPrimary: z.boolean() });
type AccountInput = z.input<typeof accountSchema>;
type AccountValues = z.output<typeof accountSchema>;

export function CrmCreateDialogs({ companies }: { companies: Array<{ id: string; name: string; type: string }> }) {
  return <div className="flex flex-wrap gap-2"><CreateAccountDialog /><CreateContactDialog companies={companies} /></div>;
}

function CreateAccountDialog() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const form = useForm<AccountInput, unknown, AccountValues>({ resolver: zodResolver(accountSchema), defaultValues: { name: "", type: "client", currency: "GBP", paymentTermsDays: 30, financeEmail: "", bookingClearance: "clear" } });
  async function save(values: AccountValues) { setError(""); const response = await fetch("/api/crm/companies", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, currency: values.currency.toUpperCase(), paymentTermsDays: values.paymentTermsDays ?? null, financeEmail: values.financeEmail || null }) }); const body = await response.json().catch(() => null); if (!response.ok) return setError(body?.error ?? "Could not create the account."); setOpen(false); router.push(`/crm/accounts/${body.id}`); router.refresh(); }
  return <><Button variant="primary" onPress={() => setOpen(true)} className="bg-[#263130] text-white"><Plus size={15} /> New account</Button>{open && <Dialog title="New account" description="Create a client, production company, network, studio, or vendor account." onClose={() => setOpen(false)}><form className="space-y-4" onSubmit={form.handleSubmit(save)}><Field label="Account name" error={form.formState.errors.name?.message}><input {...form.register("name")} placeholder="Example Television" /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Account type" error={form.formState.errors.type?.message}><select {...form.register("type")}><option value="client">Client</option><option value="production_company">Production company</option><option value="network">Network / streamer</option><option value="studio">Studio</option><option value="vendor">Vendor / supplier</option></select></Field><Field label="Currency" error={form.formState.errors.currency?.message}><input {...form.register("currency")} /></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Payment terms (days)" error={form.formState.errors.paymentTermsDays?.message}><input type="number" min="0" {...form.register("paymentTermsDays", { valueAsNumber: true })} /></Field><Field label="Booking clearance" error={form.formState.errors.bookingClearance?.message}><select {...form.register("bookingClearance")}><option value="clear">Clear to book</option><option value="po_required">Authorisation required</option><option value="finance_approval">Finance approval required</option><option value="on_hold">On hold</option></select></Field></div><Field label="Finance email" error={form.formState.errors.financeEmail?.message}><input type="email" {...form.register("financeEmail")} placeholder="finance@example.com" /></Field><Actions error={error} saving={form.formState.isSubmitting} onCancel={() => setOpen(false)} label="Create account" /></form></Dialog>}</>;
}

function CreateContactDialog({ companies }: { companies: Array<{ id: string; name: string; type: string }> }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const form = useForm<z.infer<typeof contactSchema>>({ resolver: zodResolver(contactSchema), defaultValues: { companyId: "", name: "", title: "", email: "", phone: "", contactType: "general", isPrimary: false } });
  async function save(values: z.infer<typeof contactSchema>) { setError(""); const response = await fetch("/api/crm/contacts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, title: values.title || null, email: values.email || null, phone: values.phone || null, notes: null }) }); const body = await response.json().catch(() => null); if (!response.ok) return setError(body?.error ?? "Could not create the contact."); setOpen(false); router.refresh(); }
  return <><Button variant="secondary" onPress={() => setOpen(true)} className="border border-[#dfe3df] bg-white text-[#58635e]"><UserPlus size={15} /> New contact</Button>{open && <Dialog title="New contact" description="Add an operational contact to an existing account." onClose={() => setOpen(false)}><form className="space-y-4" onSubmit={form.handleSubmit(save)}><Field label="Account" error={form.formState.errors.companyId?.message}><select {...form.register("companyId")}><option value="">Choose account</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.name} · {company.type.replaceAll("_", " ")}</option>)}</select></Field><Field label="Contact name" error={form.formState.errors.name?.message}><input {...form.register("name")} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Job title" error={form.formState.errors.title?.message}><input {...form.register("title")} /></Field><Field label="Operational purpose" error={form.formState.errors.contactType?.message}><select {...form.register("contactType")}><option value="general">General</option><option value="creative_approval">Creative approval</option><option value="technical_delivery">Technical delivery / QC</option><option value="finance">Finance / billing</option><option value="legal">Legal / compliance</option><option value="client_review">Client review</option></select></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Email" error={form.formState.errors.email?.message}><input type="email" {...form.register("email")} /></Field><Field label="Phone" error={form.formState.errors.phone?.message}><input {...form.register("phone")} /></Field></div><label className="flex items-center gap-2 text-xs text-[#535b57]"><input type="checkbox" {...form.register("isPrimary")} /> Primary contact for this purpose</label><Actions error={error} saving={form.formState.isSubmitting} onCancel={() => setOpen(false)} label="Create contact" /></form></Dialog>}</>;
}

function Dialog({ title, description, onClose, children }: { title: string; description: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#202725]/25 p-4"><div className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-xl border border-[#e2e3de] bg-[#fafbf9] p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold tracking-[-0.03em] text-[#2d3431]">{title}</h2><p className="mt-1 text-sm text-[#767c78]">{description}</p></div><Button isIconOnly variant="tertiary" onPress={onClose} aria-label="Close"><X size={18} /></Button></div><div className="mt-6">{children}</div></div></div>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-xs font-medium text-[#535b57]">{label}<span className="mt-1.5 block [&_input]:h-10 [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-[#dedfda] [&_input]:bg-white [&_input]:px-3 [&_input]:text-sm [&_select]:h-10 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-[#dedfda] [&_select]:bg-white [&_select]:px-2 [&_select]:text-sm">{children}</span>{error && <span className="mt-1 block text-[11px] font-normal text-[#a35e41]">{error}</span>}</label>; }
function Actions({ error, saving, onCancel, label }: { error: string; saving: boolean; onCancel: () => void; label: string }) { return <><>{error && <p role="alert" className="text-xs text-[#a35e41]">{error}</p>}</><div className="flex justify-end gap-2 border-t border-[#ecebe7] pt-4"><Button type="button" variant="tertiary" onPress={onCancel}>Cancel</Button><Button type="submit" variant="primary" isDisabled={saving} className="bg-[#263130] text-white">{saving ? "Saving…" : label}</Button></div></>; }
