"use client";
import { Button } from "@heroui/react";
import { Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Assignment = { id: string; personId: string; name: string; role: string; responsibility: string; isLead: boolean };
type Person = { id: string; name: string; role: string };
export function EpisodeTeam({ episodeId, assignments, people, canManage, onChanged }: { episodeId: string; assignments: Assignment[]; people: Person[]; canManage: boolean; onChanged?: () => void | Promise<void> }) {
  const router = useRouter(); const [personId, setPersonId] = useState(""); const [error, setError] = useState("");
  const availablePeople = people.filter((person) => !assignments.some((assignment) => assignment.personId === person.id));
  async function add() { const response = await fetch(`/api/episodes/${episodeId}/team`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ personId }) }); if (!response.ok) return setError((await response.json()).error ?? "Could not assign person."); setPersonId(""); await onChanged?.(); router.refresh(); }
  async function remove(id: string) { const response = await fetch(`/api/episodes/${episodeId}/team?assignmentId=${id}`, { method: "DELETE" }); if (!response.ok) return setError((await response.json()).error ?? "Could not remove person."); await onChanged?.(); router.refresh(); }
  return <div className="min-w-0 rounded-lg border border-[#ecebe7] p-3"><div className="flex items-center justify-between gap-2"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#7d837f]">Episode team</p><span className="text-[10px] text-[#858a87]">{assignments.length} assigned</span></div><div className="mt-2 space-y-1.5">{assignments.map((item) => <div key={item.id} className="flex items-center justify-between gap-2 rounded bg-[#fafaf8] px-2 py-1.5 text-xs"><span className="min-w-0 truncate font-medium text-[#46504b]">{item.name} · {item.role.replaceAll("_", " ")}</span>{canManage && <Button type="button" isIconOnly size="sm" variant="tertiary" onPress={() => remove(item.id)} aria-label={`Remove ${item.name}`} className="min-w-0 text-[#9b5c42]"><X size={13} /></Button>}</div>)}{!assignments.length && <p className="text-xs text-[#858a87]">No people assigned to this episode.</p>}</div>{canManage && <div className="mt-3 grid min-w-0 grid-cols-[minmax(0,1fr)_auto] gap-2"><select value={personId} onChange={(event) => setPersonId(event.target.value)} disabled={!availablePeople.length} className="min-w-0 max-w-full"><option value="">{availablePeople.length ? "Choose person" : "All people are assigned"}</option>{availablePeople.map((person) => <option key={person.id} value={person.id}>{person.name} · {person.role.replaceAll("_", " ")}</option>)}</select><Button type="button" isIconOnly variant="tertiary" onPress={add} isDisabled={!personId} aria-label="Add episode team member" className="min-w-0 border border-[#dfe3df]"><Plus size={15} /></Button></div>}{error && <p className="mt-2 text-xs text-[#a35e41]">{error}</p>}</div>;
}
