"use client";

import Link from "next/link";
import { Filter, TriangleAlert } from "lucide-react";
import { useMemo, useState } from "react";

export type EpisodeTableRow = {
  id: string; code: string | null; title: string; number: number; showId: string; showTitle: string; seasonNumber: number; workflowStage: string | null; editorName: string | null; producerName: string | null; lockedCutDate: string | null; deliveryDeadline: Date | null; qcStatus: string; status: string;
};

export function EpisodesTable({ episodes }: { episodes: EpisodeTableRow[] }) {
  const [show, setShow] = useState("all"); const [status, setStatus] = useState("all"); const [stage, setStage] = useState("all"); const [person, setPerson] = useState("all"); const [risk, setRisk] = useState("all");
  const options = useMemo(() => ({ shows: [...new Set(episodes.map((episode) => episode.showTitle))], statuses: [...new Set(episodes.map((episode) => episode.status))], stages: [...new Set(episodes.map((episode) => episode.workflowStage).filter((value): value is string => Boolean(value)))], people: [...new Set(episodes.flatMap((episode) => [episode.editorName, episode.producerName]).filter((value): value is string => Boolean(value)))] }), [episodes]);
  const [soon] = useState(() => new Date(Date.now() + 7 * 86_400_000));
  const filtered = episodes.filter((episode) => (show === "all" || episode.showTitle === show) && (status === "all" || episode.status === status) && (stage === "all" || episode.workflowStage === stage) && (person === "all" || episode.editorName === person || episode.producerName === person) && (risk === "all" || (risk === "at_risk" ? episode.qcStatus === "needs_attention" || (episode.deliveryDeadline && episode.deliveryDeadline <= soon) : episode.deliveryDeadline && episode.deliveryDeadline > soon)));
  return <div className="space-y-4"><div className="panel flex flex-wrap items-center gap-2 p-3"><span className="mr-1 flex items-center gap-1 text-xs font-semibold text-[#65706b]"><Filter size={14} /> Filters</span><Select value={show} onChange={setShow} label="Show" options={options.shows} /><Select value={status} onChange={setStatus} label="Status" options={options.statuses} /><Select value={stage} onChange={setStage} label="Workflow" options={options.stages} /><Select value={person} onChange={setPerson} label="Person" options={options.people} /><select aria-label="Deadline risk" value={risk} onChange={(event) => setRisk(event.target.value)} className="h-8 rounded-md border border-[#e0e1dc] bg-white px-2 text-xs text-[#59615e]"><option value="all">All deadlines</option><option value="at_risk">At risk</option><option value="on_track">On track</option></select><span className="ml-auto text-xs text-[#818783]">{filtered.length} episodes</span></div>
    <section className="panel overflow-x-auto"><div className="min-w-[1030px]"><div className="grid grid-cols-[92px_minmax(210px,1.5fr)_130px_74px_130px_125px_125px_105px_106px] gap-3 border-b border-[#ebeae6] bg-[#fafaf8] px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.08em] text-[#7e837f]"><span>Episode</span><span>Title</span><span>Show</span><span>Season</span><span>Workflow</span><span>Editor</span><span>Producer</span><span>Lock</span><span>QC</span></div><div className="divide-y divide-[#efeeea]">{filtered.map((episode) => <Link href={`/episodes/${episode.id}`} key={episode.id} className="grid grid-cols-[92px_minmax(210px,1.5fr)_130px_74px_130px_125px_125px_105px_106px] items-center gap-3 px-5 py-3.5 transition duration-150 hover:bg-[#eef4f0] hover:shadow-[inset_3px_0_0_#66877f]"><span className="font-mono text-xs font-semibold text-[#5a6964]">{episode.code ?? `E${String(episode.number).padStart(2, "0")}`}</span><span className="truncate text-sm font-medium text-[#3c4440]">{episode.title}</span><span className="truncate text-xs text-[#737a76]">{episode.showTitle}</span><span className="text-xs text-[#626965]">S{episode.seasonNumber}</span><span className="truncate text-xs capitalize text-[#616c67]">{episode.workflowStage?.replaceAll("_", " ") ?? "—"}</span><span className="truncate text-xs text-[#5e6763]">{episode.editorName ?? "—"}</span><span className="truncate text-xs text-[#5e6763]">{episode.producerName ?? "—"}</span><span className="text-xs text-[#777d79]">{episode.lockedCutDate ? new Intl.DateTimeFormat("en-GB", { month: "short", day: "numeric" }).format(new Date(episode.lockedCutDate)) : "—"}</span><span className={`flex w-fit items-center gap-1 rounded-full px-2 py-1 text-[10px] font-semibold ${episode.qcStatus === "needs_attention" ? "bg-[#f8e5dc] text-[#a55f42]" : "bg-[#edf1ee] text-[#5e746d]"}`}>{episode.qcStatus === "needs_attention" && <TriangleAlert size={11} />}{episode.qcStatus.replaceAll("_", " ")}</span></Link>)}{!filtered.length && <div className="px-5 py-10 text-center text-sm text-[#858a87]">No episodes match these filters.</div>}</div></div></section></div>;
}

function Select({ value, onChange, label, options }: { value: string; onChange: (value: string) => void; label: string; options: string[] }) { return <select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="h-8 max-w-[150px] rounded-md border border-[#e0e1dc] bg-white px-2 text-xs text-[#59615e]"><option value="all">All {label.toLowerCase()}s</option>{options.map((option) => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select>; }
