"use client";

import { AlertTriangle, ChevronRight, ClipboardList, Link2, TrendingDown, TrendingUp } from "lucide-react";
import Link from "next/link";

import { BudgetLineForm } from "@/components/budget-line-form";
import type { EstimateOverview } from "@/components/estimate-revision-panel";
import { CommercialTreatmentBadge, CommercialTreatmentSummary, type CommercialTreatment } from "@/components/commercial-treatment";

type BudgetLine = {
  id: string; workOrderId: string | null; vendorInvoiceId: string | null; purchaseOrderId: string | null; purchaseOrderNumber: string | null; purchaseOrderAllocationId: string | null; externalCost: boolean; episodeId: string | null; episodeTitle: string | null; episodeNumber: number | null; category: string; description: string | null; budgetedAmount: string | number; actualAmount: string | number; currency: string; costType: string;
};
type Resources = { services: Array<{ id: string; name: string; category: string; unit: string }>; rooms: Array<{ id: string; name: string; type: string }>; people: Array<{ id: string; name: string; role: string }>; vendors: Array<{ id: string; name: string }> };
type PurchaseOrder = { id: string; poNumber: string; vendorName: string | null; showId: string | null; episodeId: string | null; status: string; remainingAmount: number; currency: string };
export type OperationalLedger = {
  estimateItems: BudgetLine[];
  actuals: Array<{ id: string; amount: number; currency: string; allocationDate: string; sourceType: string; commercialTreatment: CommercialTreatment | null; reference: string | null; reason: string | null; budgetItem: { id: string; category: string; description: string | null }; booking: { id: string; title: string; roomName: string | null; personName: string | null } | null; timeSubmission: { actualStartsAt: string | null; actualEndsAt: string | null; approvedOvertimeMinutes: number } | null; workOrder: { id: string; title: string; status: string } | null; vendorInvoice: { id: string; invoiceNumber: string; description: string | null; invoiceDate: string | null; status: string } | null }>;
  unallocatedActuals: Array<{ componentId: string; componentType: string; commercialTreatment: CommercialTreatment; resourceName: string; amount: number; currency: string; bookingId: string; bookingTitle: string; actualStartsAt: string | null; actualEndsAt: string | null; approvedOvertimeMinutes: number; selectedBudgetItem: { id: string; category: string; description: string | null } | null; reason: string }>;
};

export function EpisodeBudgetOperations({ estimate, lines, ledger, episodes, resources, purchaseOrders }: { estimate: EstimateOverview; lines: BudgetLine[]; ledger: OperationalLedger; episodes: Array<{ id: string; label: string; showId?: string }>; resources: Resources; purchaseOrders: PurchaseOrder[] }) {
  const approvedEstimate = estimate.currentApprovedEstimate ?? estimate.workingEstimate;
  const variance = estimate.variance ?? estimate.forecast - approvedEstimate;
  const remainingByLine = new Map(lines.map((line) => [line.id, Math.max(0, Number(line.budgetedAmount) - Number(line.actualAmount))]));
  return <div className="space-y-4">
    <section className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      <SummaryCard title="Estimate" value={money(approvedEstimate, estimate.currency)} detail={estimate.currentApprovedEstimate === null ? "Working plan — not yet approved" : "Current approved episode estimate"} icon={<ClipboardList size={16} />} />
      <SummaryCard title="Actuals" value={money(estimate.actual, estimate.currency)} detail={`${ledger.actuals.length} allocated source${ledger.actuals.length === 1 ? "" : "s"}`} icon={<TrendingDown size={16} />} />
      <SummaryCard title="Forecast" value={money(estimate.forecast, estimate.currency)} detail={`Actuals + ${money(estimate.remainingPlanned, estimate.currency)} remaining plan`} icon={<TrendingUp size={16} />} attention={estimate.forecast > approvedEstimate} />
      <SummaryCard title="Variance" value={`${variance > 0 ? "+" : ""}${money(variance, estimate.currency)}`} detail={variance > 0 ? "Forecast above current estimate" : "Within current estimate"} icon={<AlertTriangle size={16} />} attention={variance > 0} />
    </section>

    {estimate.commercialForecast.agreedFlatFeeRevenue > 0 && <section className={`overflow-hidden rounded-xl border ${estimate.commercialForecast.flatFeeMarginAtRisk ? "border-[#ead5c7] bg-[#fffaf6]" : "border-[#dbe7df] bg-[#fbfdfb]"}`}>
      <div className="flex flex-col justify-between gap-3 px-5 py-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className={`text-sm font-semibold ${estimate.commercialForecast.flatFeeMarginAtRisk ? "text-[#8a5038]" : "text-[#3e7160]"}`}>Flat-project-fee commercial position</p><CommercialTreatmentBadge treatment="flat_project_fee" /></div><CommercialTreatmentSummary treatment="flat_project_fee" className="mt-1 max-w-2xl" /><p className="mt-1 text-xs leading-5 text-[#737d78]">Overtime affects internal cost and margin, not the agreed fee.</p></div><span className={`text-sm font-semibold ${estimate.commercialForecast.flatFeeMarginAtRisk ? "text-[#a35e41]" : "text-[#3e7160]"}`}>{estimate.commercialForecast.flatFeeMarginAtRisk ? "Margin at risk" : "Margin within agreed fee"}</span></div>
      <div className="grid divide-y divide-[#e7ebe7] border-t border-[#e7ebe7] sm:grid-cols-4 sm:divide-x sm:divide-y-0"><CommercialMetric label="Agreed fee revenue" value={estimate.commercialForecast.agreedFlatFeeRevenue} currency={estimate.currency} /><CommercialMetric label="Internal actual" value={estimate.commercialForecast.flatFeeInternalActual} currency={estimate.currency} /><CommercialMetric label="Internal cost forecast" value={estimate.commercialForecast.flatFeeInternalForecast} currency={estimate.currency} /><CommercialMetric label="Forecast margin" value={estimate.commercialForecast.flatFeeForecastMargin} currency={estimate.currency} attention={estimate.commercialForecast.flatFeeMarginAtRisk} /></div>
    </section>}

    {ledger.unallocatedActuals.length > 0 && <section className="overflow-hidden rounded-xl border border-[#ead5c7] bg-[#fffaf6]">
      <div className="flex flex-col justify-between gap-2 border-b border-[#f0ddd1] px-5 py-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-sm font-semibold text-[#7d4935]"><AlertTriangle size={16} /> Unallocated operational actuals</div><p className="mt-1 text-xs text-[#956a58]">These saved room or artist costs were not matched to an episode estimate item. They remain in the forecast, but need commercial review.</p></div><span className="w-fit rounded-full bg-[#fae7da] px-2 py-1 text-xs font-semibold text-[#925238]">{ledger.unallocatedActuals.length} needs attention</span></div>
      <div className="divide-y divide-[#f1e2d9]">{ledger.unallocatedActuals.map((entry) => <div key={entry.componentId} className="flex flex-col justify-between gap-3 px-5 py-3 sm:flex-row sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-[#54423b]">{entry.resourceName} · {money(entry.amount, entry.currency)}</p><CommercialTreatmentBadge treatment={entry.commercialTreatment} /></div><p className="mt-1 text-xs text-[#83665a]">{entry.bookingTitle} · {entry.componentType.replaceAll("_", " ")} · {timeRange(entry.actualStartsAt, entry.actualEndsAt)}{entry.approvedOvertimeMinutes ? ` · ${entry.approvedOvertimeMinutes}m approved overtime` : ""}</p><CommercialTreatmentSummary treatment={entry.commercialTreatment} className="mt-1 text-[11px] leading-4" /><p className="mt-1 text-xs text-[#9a5c43]">{entry.reason}</p></div><Link href={`/bookings?booking=${entry.bookingId}`} className="inline-flex shrink-0 items-center gap-1 text-xs font-semibold text-[#7b5848] hover:underline">Open booking <ChevronRight size={14} /></Link></div>)}</div>
    </section>}

    <BudgetSection title="Estimate" description="Approved planned items. Expand an item to inspect its estimate source and operational links.">
      {!lines.length ? <Empty message="No planned budget items are linked to this episode." /> : <div className="divide-y divide-[#efeeea]">{lines.map((line) => <details key={line.id} className="group"><summary className="grid cursor-pointer list-none gap-2 px-5 py-3 text-sm sm:grid-cols-[minmax(0,1fr)_120px_120px_24px] sm:items-center"><div className="min-w-0"><p className="truncate font-semibold text-[#3f4944]">{line.category}</p><p className="mt-0.5 truncate text-xs text-[#858a87]">{line.description ?? "No description"}</p></div><span className="font-medium text-[#4d5752]">{money(Number(line.budgetedAmount), line.currency)}</span><span className="text-xs text-[#737d78]">{line.externalCost ? "External vendor" : "Internal"}</span><ChevronRight size={16} className="justify-self-end text-[#8b928e] transition-transform group-open:rotate-90" /></summary><div className="grid gap-3 border-t border-[#f2f1ed] bg-[#fafaf8] px-5 py-3 text-xs text-[#64706a] sm:grid-cols-2"><div><p className="font-semibold text-[#4b5651]">Budget item source</p><p className="mt-1">{line.category}{line.description ? ` · ${line.description}` : ""}</p><p className="mt-1">Selected cost type: {line.costType}</p></div><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[#4b5651]">Operational links</p><p className="mt-1">{line.workOrderId ? "Linked work order" : line.vendorInvoiceId ? "Supplier invoice source" : "Manual / rate-card planned item"}</p>{line.purchaseOrderNumber && <p className="mt-1">Vendor PO · {line.purchaseOrderNumber}</p>}</div>{!line.workOrderId && !line.vendorInvoiceId && <BudgetLineForm episodes={episodes} currency={line.currency} purchaseOrders={purchaseOrders} resources={resources} line={line} locked={estimate.isLocked} />}</div></div></details>)}</div>}
    </BudgetSection>

    <BudgetSection title="Actuals" description="Recorded allocations only. Each amount links back to the budget item and source operational record.">
      {!ledger.actuals.length ? <Empty message="No actual cost allocations have been recorded yet." /> : <div className="divide-y divide-[#efeeea]">{ledger.actuals.map((actual) => <details key={actual.id} className="group"><summary className="grid cursor-pointer list-none gap-2 px-5 py-3 text-sm sm:grid-cols-[minmax(0,1fr)_130px_24px] sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-semibold text-[#3f4944]">{sourceLabel(actual.sourceType)} · {actual.budgetItem.description ?? actual.budgetItem.category}</p>{actual.commercialTreatment && <CommercialTreatmentBadge treatment={actual.commercialTreatment} />}</div><p className="mt-0.5 truncate text-xs text-[#858a87]">{actual.allocationDate ? formatDate(actual.allocationDate) : "Recorded actual"}</p></div><span className="font-medium text-[#4d5752]">{money(actual.amount, actual.currency)}</span><ChevronRight size={16} className="justify-self-end text-[#8b928e] transition-transform group-open:rotate-90" /></summary><div className="grid gap-3 border-t border-[#f2f1ed] bg-[#fafaf8] px-5 py-3 text-xs text-[#64706a] sm:grid-cols-2"><Trace title="Budget item" detail={`${actual.budgetItem.category}${actual.budgetItem.description ? ` · ${actual.budgetItem.description}` : ""}`} /><div className="space-y-2">{actual.commercialTreatment && <div><p className="font-semibold text-[#4b5651]">Commercial treatment</p><CommercialTreatmentSummary treatment={actual.commercialTreatment} className="mt-0.5" /></div>}<Trace title="Booking" detail={actual.booking ? `${actual.booking.title} · ${actual.booking.roomName ?? "No room"} · ${actual.booking.personName ?? "No assigned person"}` : "Not linked"} href={actual.booking ? `/bookings?booking=${actual.booking.id}` : undefined} />{actual.timeSubmission && <Trace title="Time submission" detail={`${timeRange(actual.timeSubmission.actualStartsAt, actual.timeSubmission.actualEndsAt)}${actual.timeSubmission.approvedOvertimeMinutes ? ` · ${actual.timeSubmission.approvedOvertimeMinutes}m approved overtime` : ""}`} />}{actual.workOrder && <Trace title="Work order" detail={`${actual.workOrder.title} · ${actual.workOrder.status.replaceAll("_", " ")}`} />}{actual.vendorInvoice && <Trace title="Vendor invoice" detail={`${actual.vendorInvoice.invoiceNumber}${actual.vendorInvoice.description ? ` · ${actual.vendorInvoice.description}` : ""} · ${actual.vendorInvoice.status}`} />}{actual.reason && <Trace title="Reason" detail={actual.reason} />}{actual.reference && <Trace title="Reference" detail={actual.reference} />}</div></div></details>)}</div>}
    </BudgetSection>

    <section className="grid gap-4 xl:grid-cols-2">
      <BudgetSection title="Forecast" description="Recorded actuals plus the remaining plan on each budget item."><div className="divide-y divide-[#efeeea]">{lines.map((line) => <details key={line.id} className="group"><summary className="grid cursor-pointer list-none gap-2 px-5 py-3 text-sm sm:grid-cols-[minmax(0,1fr)_115px_115px_24px] sm:items-center"><span className="truncate font-medium text-[#424c47]">{line.description ?? line.category}</span><span className="text-xs text-[#69736e]">Actual {money(Number(line.actualAmount), line.currency)}</span><span className="font-medium text-[#3e7160]">Left {money(remainingByLine.get(line.id) ?? 0, line.currency)}</span><ChevronRight size={16} className="justify-self-end text-[#8b928e] transition-transform group-open:rotate-90" /></summary><div className="border-t border-[#f2f1ed] bg-[#fafaf8] px-5 py-3 text-xs text-[#64706a]">Forecast contribution: {money(Number(line.actualAmount) + (remainingByLine.get(line.id) ?? 0), line.currency)}. This is based on {money(Number(line.actualAmount), line.currency)} recorded actuals plus the remaining planned cost.</div></details>)}</div></BudgetSection>
      <BudgetSection title="Variance" description="Forecast compared with the current approved estimate."><details className="group"><summary className="grid cursor-pointer list-none gap-2 px-5 py-4 text-sm sm:grid-cols-[minmax(0,1fr)_130px_24px] sm:items-center"><span className="font-semibold text-[#424c47]">Episode forecast variance</span><span className={variance > 0 ? "font-semibold text-[#a35e41]" : "font-semibold text-[#3e7160]"}>{variance > 0 ? "+" : ""}{money(variance, estimate.currency)}</span><ChevronRight size={16} className="justify-self-end text-[#8b928e] transition-transform group-open:rotate-90" /></summary><div className="grid gap-2 border-t border-[#f2f1ed] bg-[#fafaf8] px-5 py-3 text-xs text-[#64706a]"><p>Current approved estimate · {money(approvedEstimate, estimate.currency)}</p><p>Forecast · {money(estimate.forecast, estimate.currency)}</p><p>{variance > 0 ? "Forecast is above the approved estimate. Review the affected items or create a named estimate revision." : "Forecast remains within the approved estimate."}</p></div></details></BudgetSection>
    </section>
  </div>;
}

function SummaryCard({ title, value, detail, icon, attention = false }: { title: string; value: string; detail: string; icon: React.ReactNode; attention?: boolean }) { return <div className="panel p-4"><div className={`flex items-center gap-2 text-xs font-semibold uppercase tracking-[.08em] ${attention ? "text-[#a35e41]" : "text-[#76807b]"}`}>{icon}{title}</div><p className="mt-3 text-xl font-semibold tracking-[-.035em] text-[#343d39]">{value}</p><p className="mt-1 text-xs text-[#858a87]">{detail}</p></div>; }
function CommercialMetric({ label, value, currency, attention = false }: { label: string; value: number; currency: string; attention?: boolean }) { return <div className="px-5 py-3"><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#858a87]">{label}</p><p className={`mt-1 text-sm font-semibold ${attention ? "text-[#a35e41]" : "text-[#3d4943]"}`}>{money(value, currency)}</p></div>; }
function BudgetSection({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="panel overflow-hidden"><div className="border-b border-[#ebeae6] px-5 py-4"><h2 className="text-sm font-semibold text-[#343b38]">{title}</h2><p className="mt-1 text-xs text-[#858a87]">{description}</p></div>{children}</section>; }
function Empty({ message }: { message: string }) { return <p className="px-5 py-10 text-center text-sm text-[#858a87]">{message}</p>; }
function Trace({ title, detail, href }: { title: string; detail: string; href?: string }) { return <div><p className="font-semibold text-[#4b5651]">{title}</p>{href ? <Link href={href} className="mt-0.5 inline-flex items-center gap-1 text-[#4e756a] hover:underline">{detail}<Link2 size={11} /></Link> : <p className="mt-0.5">{detail}</p>}</div>; }
function money(value: number, currency: string) { try { return new Intl.NumberFormat("en-GB", { style: "currency", currency, minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); } catch { return `${currency} ${value.toFixed(2)}`; } }
function sourceLabel(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }
function timeRange(start: string | null, end: string | null) { if (!start || !end) return "No submitted time range"; const format = new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", hour12: false }); return `${format.format(new Date(start))}–${new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(end))}`; }
