"use client";

import { Button } from "@heroui/react";
import { Pencil } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";

import { MasterServiceRateDialog, RemoveMasterServiceRateButton, type ServiceRate } from "@/components/service-rate-card";
import { postpilotUiFetch } from "@/lib/postpilot-api-client";

const billingUnits = [["hour", "Hourly"], ["day", "Day"], ["fixed", "Fixed fee"]] as const;
type BillingUnit = (typeof billingUnits)[number][0];
type Scope = { type: "master" } | { type: "network"; network: string } | { type: "show"; showId: string } | { type: "episode"; episodeId: string };
type Price = { id?: string; rate: string | number; currency: string };
type PriceValues = Record<BillingUnit, string>;
type Group = Omit<ServiceRate, "id" | "unit" | "rate"> & { rates: ServiceRate[] };

function scopeQuery(scope: Scope) { return new URLSearchParams(scope.type === "master" ? { scope: "master" } : scope.type === "network" ? { scope: scope.type, network: scope.network } : scope.type === "show" ? { scope: scope.type, show_id: scope.showId } : { scope: scope.type, episode_id: scope.episodeId }); }
function money(value: string | number, currency: string) { return new Intl.NumberFormat("en-GB", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value)); }
function blank(): PriceValues { return { hour: "", day: "", fixed: "" }; }

/** A service card shows the three possible selling structures on one service row. */
export function RateOverrideCard({ rates, scope, title }: { rates: ServiceRate[]; scope: Scope; title: string }) {
  const [overrides, setOverrides] = useState<Record<string, Price>>({}); const [inherited, setInherited] = useState<Record<string, Price>>({}); const query = scopeQuery(scope).toString();
  useEffect(() => { let cancelled = false; postpilotUiFetch(`/v1/rate-cards/overrides?${query}`).then((response) => response.ok ? response.json() : null).then((body) => { if (!cancelled) { setOverrides(body?.overrides ?? {}); setInherited(body?.inherited ?? {}); } }).catch(() => undefined); return () => { cancelled = true; }; }, [query]);
  const groups = useMemo(() => Object.values(rates.reduce<Record<string, Group>>((all, rate) => { const key = [rate.name, rate.category, rate.artistRole ?? ""].join("\u0000"); all[key] ??= { name: rate.name, category: rate.category, artistRole: rate.artistRole, currency: rate.currency, notes: rate.notes, isActive: rate.isActive, rates: [] }; all[key].rates.push(rate); return all; }, {})), [rates]);
  const isMaster = scope.type === "master";
  return <section className="panel overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-[#ebeae6] px-5 py-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold text-[#343b38]">{title}</h2><p className="mt-1 text-xs text-[#858a87]">{isMaster ? "Your post house defaults. Add Hourly, Day, and Fixed fee prices to the same service where required." : "Prices inherit from the level above. Override only the billing structures agreed at this scope."}</p></div>{isMaster && <MasterServiceRateDialog />}</div><div className="divide-y divide-[#efeeea]">{groups.map((group) => <RateRow key={`${group.name}:${group.category}:${group.artistRole ?? ""}`} group={group} scope={scope} overrides={overrides} inherited={inherited} onChanged={(nextOverrides) => setOverrides(nextOverrides)} />)}{!groups.length && <p className="px-5 py-8 text-sm text-[#858a87]">No standard resource rates are available.</p>}</div></section>;
}

function RateRow({ group, scope, overrides, inherited, onChanged }: { group: Group; scope: Scope; overrides: Record<string, Price>; inherited: Record<string, Price>; onChanged: (next: Record<string, Price>) => void }) {
  const [open, setOpen] = useState(false); const isMaster = scope.type === "master";
  const price = (unit: BillingUnit) => { const source = group.rates.find((rate) => rate.unit === unit); return source ? { source, own: overrides[`${source.category}:${unit}`], inherited: inherited[`${source.category}:${unit}`] } : null; };
  const configured = billingUnits.map(([unit]) => price(unit));
  return <div className="flex flex-col justify-between gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="min-w-0"><p className="text-sm font-medium text-[#3d4642]">{group.name}</p><p className="mt-1 text-xs text-[#858a87]">{group.artistRole ? `Artist role · ${group.artistRole.replaceAll("_", " ")}` : group.category}</p></div><div className="flex flex-wrap items-center gap-2 sm:justify-end"><div className="grid grid-cols-3 gap-2 text-right text-xs">{billingUnits.map(([unit, label]) => { const entry = price(unit); const value = entry?.own ?? entry?.inherited ?? (entry?.source ? { rate: entry.source.rate, currency: entry.source.currency } : null); return <div key={unit}><p className="text-[#858a87]">{label}</p><p className="font-semibold text-[#3d4642]">{value ? money(value.rate, value.currency) : "—"}</p></div>; })}</div>{isMaster ? <><MasterServiceRateDialog rates={group.rates} /><RemoveMasterServiceRateButton rates={group.rates} /></> : <><Button size="sm" variant="tertiary" onPress={() => setOpen(true)} className="min-w-0 border border-[#dfe3df] bg-white text-[#58635e]"><Pencil size={13} /> {configured.some((entry) => entry?.own) ? "Edit override" : "Override"}</Button>{open && <OverrideDialog group={group} scope={scope} overrides={overrides} inherited={inherited} onClose={() => setOpen(false)} onSaved={onChanged} />}</>}</div></div>;
}

function OverrideDialog({ group, scope, overrides, inherited, onClose, onSaved }: { group: Group; scope: Scope; overrides: Record<string, Price>; inherited: Record<string, Price>; onClose: () => void; onSaved: (next: Record<string, Price>) => void }) {
  const router = useRouter();
  const initial = billingUnits.reduce<PriceValues>((values, [unit]) => { const rate = group.rates.find((candidate) => candidate.unit === unit); const key = rate ? `${rate.category}:${unit}` : ""; values[unit] = key && overrides[key] ? String(overrides[key].rate) : ""; return values; }, blank());
  const [values, setValues] = useState<PriceValues>(initial); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function save() { setSaving(true); setError(""); const next = { ...overrides }; for (const [unit] of billingUnits) { const source = group.rates.find((rate) => rate.unit === unit); if (!source) continue; const key = `${source.category}:${unit}`; const value = values[unit].trim(); const existing = overrides[key]; if (!value) { if (existing?.id) { const response = await postpilotUiFetch(`/v1/rate-cards/items/${existing.id}`, { method: "DELETE" }); if (!response.ok) { setSaving(false); return setError("Could not remove the cleared override."); } delete next[key]; } continue; } if (Number(value) <= 0) { setSaving(false); return setError("Override prices must be greater than zero."); } const response = await postpilotUiFetch("/v1/rate-cards/overrides", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scope: scope.type, network: scope.type === "network" ? scope.network : null, showId: scope.type === "show" ? scope.showId : null, episodeId: scope.type === "episode" ? scope.episodeId : null, serviceRateId: source.id, rate: Number(value) }) }); const body = await response.json().catch(() => null); if (!response.ok) { setSaving(false); return setError(body?.detail ?? body?.error ?? "Could not save the override."); } next[key] = { id: body?.items?.find?.((item: { category: string; unit: string }) => item.category === source.category && item.unit === unit)?.id, rate: value, currency: source.currency }; } onSaved(next); router.refresh(); onClose(); }
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-[#202725]/30 p-4" role="dialog" aria-modal="true" aria-labelledby="service-override-title"><div className="w-full max-w-xl rounded-xl border border-[#e2e3de] bg-[#fafbf9] p-6 shadow-2xl"><h3 id="service-override-title" className="text-lg font-semibold text-[#2d3431]">Override {group.name}</h3><p className="mt-1 text-sm text-[#767c78]">Leave a price empty to continue inheriting it. This never changes the master rate card.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{billingUnits.map(([unit, label]) => { const supported = Boolean(group.rates.find((rate) => rate.unit === unit)); const inheritedPrice = inherited[`${group.category}:${unit}`]; return <label key={unit} className="text-xs font-medium text-[#535b57]">{label}<input disabled={!supported} value={values[unit]} onChange={(event) => setValues((current) => ({ ...current, [unit]: event.target.value }))} type="number" min="0" step="0.01" placeholder={!supported ? "Not offered" : inheritedPrice ? `Inherited ${money(inheritedPrice.rate, group.currency)}` : "Not set"} className="mt-1.5 h-10 w-full rounded-md border border-[#dedfda] bg-white px-3 text-sm disabled:bg-[#f1f2ef]" /></label>; })}</div>{error && <p role="alert" className="mt-3 text-xs text-[#a35e41]">{error}</p>}<div className="mt-6 flex justify-end gap-2"><Button variant="tertiary" onPress={onClose}>Cancel</Button><Button variant="primary" onPress={save} isDisabled={saving} className="bg-[#263130] text-white">{saving ? "Saving…" : "Save overrides"}</Button></div></div></div>;
}
