"use client";

import { Button } from "@heroui/react";
import { Pencil } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

import type { ServiceRate } from "@/components/service-rate-card";

type Scope = { type: "network"; network: string } | { type: "show"; showId: string } | { type: "episode"; episodeId: string };

export function RateOverrideCard({ rates, scope, title }: { rates: ServiceRate[]; scope: Scope; title: string }) {
  const [overrides, setOverrides] = useState<Record<string, { rate: string | number; currency: string }>>({});
  const [inherited, setInherited] = useState<Record<string, { rate: string | number; currency: string }>>({});
  useEffect(() => { const params = new URLSearchParams(scope.type === "network" ? { type: scope.type, network: scope.network } : scope.type === "show" ? { type: scope.type, showId: scope.showId } : { type: scope.type, episodeId: scope.episodeId }); fetch(`/api/rate-card-overrides?${params}`).then((response) => response.ok ? response.json() : null).then((body) => { setOverrides(body?.overrides ?? {}); setInherited(body?.inherited ?? {}); }).catch(() => undefined); }, [scope]);
  return <section className="panel overflow-hidden"><div className="border-b border-[#ebeae6] px-5 py-4"><h2 className="text-sm font-semibold text-[#343b38]">{title}</h2><p className="mt-1 text-xs text-[#858a87]">Prices inherit from the level above. Set an override only for an agreed exception.</p></div><div className="divide-y divide-[#efeeea]">{rates.map((rate) => <RateRow key={rate.id} rate={rate} scope={scope} override={overrides[`${rate.category}:${rate.unit}`]} inherited={inherited[`${rate.category}:${rate.unit}`]} onSaved={(override) => { const key = `${rate.category}:${rate.unit}`; setOverrides((current) => ({ ...current, [key]: override })); setInherited((current) => ({ ...current, [key]: override })); }} />)}{!rates.length && <p className="px-5 py-8 text-sm text-[#858a87]">No facility services are available to override.</p>}</div></section>;
}

function RateRow({ rate, scope, override, inherited, onSaved }: { rate: ServiceRate; scope: Scope; override?: { rate: string | number; currency: string }; inherited?: { rate: string | number; currency: string }; onSaved: (override: { rate: string | number; currency: string }) => void }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [value, setValue] = useState(String(override?.rate ?? rate.rate)); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); setError(""); const response = await fetch("/api/rate-card-overrides", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scope, serviceRateId: rate.id, rate: Number(value) }) }); const body = await response.json().catch(() => null); setSaving(false); if (!response.ok) return setError(body?.error ?? "Could not save the override."); onSaved({ rate: value, currency: rate.currency }); setOpen(false); router.refresh(); }
  const inheritedRate = inherited ?? { rate: rate.rate, currency: rate.currency };
  return <div className="flex flex-wrap items-center justify-between gap-3 px-5 py-3"><div><p className="text-sm font-medium text-[#3d4642]">{rate.name}</p><p className="mt-1 text-xs text-[#858a87]">{rate.category} · {override ? <><b className="text-[#4f7767]">override {formatMoney(override.rate, override.currency)}</b> · inherited {formatMoney(inheritedRate.rate, inheritedRate.currency)}</> : <>inherits <b className="text-[#586e65]">{formatMoney(inheritedRate.rate, inheritedRate.currency)}</b></>} / {rate.unit}</p></div><Button size="sm" variant="tertiary" onPress={() => { setValue(String(override?.rate ?? inheritedRate.rate)); setOpen(true); }} className="min-w-0 border border-[#dfe3df] bg-white text-[#58635e]"><Pencil size={13} /> {override ? "Edit override" : "Override"}</Button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#202725]/25 p-4"><div className="w-full max-w-sm rounded-xl border border-[#e2e3de] bg-[#fafbf9] p-5 shadow-2xl"><h3 className="text-base font-semibold text-[#303834]">Override {rate.name}</h3><p className="mt-1 text-xs text-[#767c78]">This price applies at this level and below until a more specific override is set.</p><label className="mt-5 block text-xs font-medium text-[#535b57]">Rate<input value={value} onChange={(event) => setValue(event.target.value)} type="number" min="0.01" step="0.01" className="mt-1.5 h-10 w-full rounded-md border border-[#dedfda] bg-white px-3 text-sm" /></label>{error && <p className="mt-2 text-xs text-[#a35e41]">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button variant="tertiary" onPress={() => setOpen(false)}>Cancel</Button><Button variant="primary" onPress={save} isDisabled={saving} className="bg-[#263130] text-white">{saving ? "Saving…" : "Save override"}</Button></div></div></div>}</div>;
}

function formatMoney(value: string | number, currency: string) { try { return new Intl.NumberFormat("en-GB", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value)); } catch { return `${currency} ${value}`; } }
