"use client";

import { ChevronLeft, ChevronRight, Clock3, Gauge } from "lucide-react";
import { Button } from "@heroui/react";
import { useMemo, useState } from "react";
import { BookingFormDialog, type BookingResources } from "@/components/booking-form-dialog";

export type ScheduleBooking = { id: string; title: string; startsAt: Date; endsAt: Date; status: string; bookingType: string; roomId: string | null; episodeId: string | null; personId: string | null; notes: string | null; roomName: string | null; roomType: string | null; episodeTitle: string | null; episodeNumber: number | null; personName: string | null };
type Span = { booking: ScheduleBooking; start: number; end: number; lane: number };

export function ScheduleBoard({ bookings, rooms, resources, initialDate }: { bookings: ScheduleBooking[]; rooms: Array<{ id: string; name: string; type: string }>; resources: BookingResources; initialDate: string }) {
  const [view, setView] = useState<"day" | "week">("week");
  const [cursor, setCursor] = useState(() => startOfDay(new Date(initialDate)));
  const [selectedBooking, setSelectedBooking] = useState<ScheduleBooking | null>(null);
  const days = useMemo(() => Array.from({ length: view === "week" ? 7 : 1 }, (_, index) => addDays(cursor, index)), [cursor, view]);
  const rangeEnd = useMemo(() => addDays(cursor, days.length), [cursor, days.length]);
  const visible = useMemo(() => bookings.filter((booking) => overlaps(booking.startsAt, booking.endsAt, cursor, rangeEnd)), [bookings, cursor, rangeEnd]);
  const bookingSpans = useMemo(() => layoutSpans(visible, cursor, days.length), [visible, cursor, days.length]);
  const utilization = rooms.map((room) => ({ ...room, hours: visible.filter((booking) => booking.roomName === room.name).reduce((sum, booking) => sum + visibleHours(booking, cursor, rangeEnd), 0) })).sort((a, b) => b.hours - a.hours);
  const move = (direction: number) => setCursor((current) => addDays(current, direction * days.length));
  return <div className="space-y-4"><section className="panel flex flex-wrap items-center justify-between gap-3 p-3"><div className="flex items-center gap-2"><Button isIconOnly variant="tertiary" onClick={() => move(-1)} className="min-w-0 border border-[#e0e1dc] text-[#6d7571] hover:bg-[#f4f4f1]" aria-label="Previous period"><ChevronLeft size={16} /></Button><p className="min-w-[180px] text-center text-sm font-semibold text-[#3e4743]">{rangeLabel(days)}</p><Button isIconOnly variant="tertiary" onClick={() => move(1)} className="min-w-0 border border-[#e0e1dc] text-[#6d7571] hover:bg-[#f4f4f1]" aria-label="Next period"><ChevronRight size={16} /></Button></div><div className="flex rounded-md border border-[#e0e1dc] bg-[#fafaf8] p-0.5"><Button variant="tertiary" onClick={() => setView("day")} className={`h-7 min-w-0 rounded px-3 text-xs font-medium ${view === "day" ? "bg-white text-[#34413d] shadow-sm" : "text-[#7b817e]"}`}>Day</Button><Button variant="tertiary" onClick={() => setView("week")} className={`h-7 min-w-0 rounded px-3 text-xs font-medium ${view === "week" ? "bg-white text-[#34413d] shadow-sm" : "text-[#7b817e]"}`}>Week</Button></div></section>
    <section className="grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_300px]"><div className="panel overflow-x-auto"><div className={view === "week" ? "min-w-[840px]" : "min-w-[480px]"}><div className={`grid ${view === "week" ? "grid-cols-7" : "grid-cols-1"}`}>{days.map((day) => <DayHeader key={day.toISOString()} day={day} />)}</div><BookingGrid spans={bookingSpans} columns={days.length} onSelect={setSelectedBooking} /></div></div><aside className="panel p-5"><div className="flex items-center gap-2"><Gauge size={16} className="text-[#71817c]" /><div><h2 className="text-sm font-semibold text-[#343c38]">Room utilization</h2><p className="mt-0.5 text-xs text-[#858a87]">Visible period</p></div></div><div className="mt-5 space-y-3.5">{utilization.map((room) => { const percent = Math.min(100, Math.round((room.hours / (view === "week" ? 40 : 9)) * 100)); return <div key={room.id}><div className="mb-1.5 flex justify-between gap-2 text-xs"><span className="truncate font-medium text-[#58615d]">{room.name}</span><span className="shrink-0 text-[#858a87]">{room.hours.toFixed(0)}h · {percent}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#ecebe7]"><div className={`h-full rounded-full ${percent > 85 ? "bg-[#bd7650]" : "bg-[#64847e]"}`} style={{ width: `${percent}%` }} /></div></div>; })}</div><div className="mt-5 border-t border-[#ecebe7] pt-4 text-xs text-[#7d837f]"><Clock3 className="mr-1 inline" size={13} /> {visible.length} bookings in view</div></aside></section>{selectedBooking && <BookingFormDialog key={selectedBooking.id} resources={resources} initialStart={toInput(cursor)} booking={selectedBooking} onClose={() => setSelectedBooking(null)} />}</div>;
}

function DayHeader({ day }: { day: Date }) { return <div className="border-b border-r border-[#ebeae6] bg-[#fafaf8] px-3 py-2.5 last:border-r-0"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#8a8f8c]">{new Intl.DateTimeFormat("en-GB", { weekday: "short" }).format(day)}</p><p className="mt-0.5 text-sm font-semibold text-[#3c4440]">{new Intl.DateTimeFormat("en-GB", { month: "short", day: "numeric" }).format(day)}</p></div>; }

function BookingGrid({ spans, columns, onSelect }: { spans: Span[]; columns: number; onSelect: (booking: ScheduleBooking) => void }) { const rows = spans.length ? Math.max(...spans.map((span) => span.lane)) + 1 : 0; return <div className="relative min-h-[400px] bg-[#fafbf9]"><div className={`pointer-events-none absolute inset-0 grid ${columns === 7 ? "grid-cols-7" : "grid-cols-1"}`}>{Array.from({ length: columns }, (_, index) => <div key={index} className="border-r border-[#ebeae6] last:border-r-0" />)}</div>{spans.length ? <div className={`relative grid gap-x-1 gap-y-2 p-2 ${columns === 7 ? "grid-cols-7" : "grid-cols-1"}`} style={{ gridTemplateRows: `repeat(${rows}, minmax(52px, auto))` }}>{spans.map((span) => <BookingBar key={span.booking.id} span={span} onSelect={onSelect} />)}</div> : <p className="relative px-4 pt-6 text-xs text-[#9a9e9b]">No bookings</p>}</div>; }

function BookingBar({ span, onSelect }: { span: Span; onSelect: (booking: ScheduleBooking) => void }) { const booking = span.booking; const color = bookingColors(booking.bookingType); return <button type="button" onClick={() => onSelect(booking)} style={{ gridColumn: `${span.start + 1} / ${span.end + 2}`, gridRow: span.lane + 1 }} className={`min-w-0 border-l-[3px] rounded-r-md p-2 text-left transition-shadow hover:shadow-md focus:outline-none focus:ring-2 focus:ring-[#66877f] ${color}`} aria-label={`Edit ${booking.title}`}><p className="truncate text-[11px] font-semibold text-[#414945]">{booking.title}</p><p className="mt-1 truncate text-[10px] text-[#68716d]">{timeLabel(booking.startsAt)}–{timeLabel(booking.endsAt)} · {booking.roomName ?? "No room"}</p><p className="mt-1 truncate text-[10px] capitalize text-[#727a76]">{booking.personName ?? "Unassigned"}</p></button>; }

function layoutSpans(bookings: ScheduleBooking[], rangeStart: Date, days: number) { const laneEnds: number[] = []; return [...bookings].sort((a, b) => a.startsAt.getTime() - b.startsAt.getTime()).map((booking) => { const start = Math.max(0, calendarDayDistance(rangeStart, booking.startsAt)); const end = Math.min(days - 1, calendarDayDistance(rangeStart, booking.endsAt)); const lane = laneEnds.findIndex((laneEnd) => laneEnd < start); const selectedLane = lane === -1 ? laneEnds.length : lane; laneEnds[selectedLane] = end; return { booking, start, end, lane: selectedLane }; }); }
function bookingColors(type: string) { return { edit: "border-l-[#5f7ee6] bg-[#eff3ff]", color: "border-l-[#9b70e5] bg-[#f5effc]", mix: "border-l-[#4f9a79] bg-[#edf7f2]", qc: "border-l-[#c2764f] bg-[#fcf1eb]", client_review: "border-l-[#c49b4b] bg-[#faf5e8]", ingest: "border-l-[#74899a] bg-[#f0f4f6]", conform: "border-l-[#817eaa] bg-[#f2f1fa]" }[type] ?? "border-l-[#74899a] bg-[#f0f4f6]"; }
function startOfDay(date: Date) { const value = new Date(date); value.setHours(0, 0, 0, 0); return value; }
function addDays(date: Date, count: number) { const value = new Date(date); value.setDate(value.getDate() + count); return value; }
function overlaps(start: Date, end: Date, rangeStart: Date, rangeEnd: Date) { return start < rangeEnd && end > rangeStart; }
function visibleHours(booking: ScheduleBooking, rangeStart: Date, rangeEnd: Date) { return Math.max(0, (Math.min(booking.endsAt.getTime(), rangeEnd.getTime()) - Math.max(booking.startsAt.getTime(), rangeStart.getTime())) / 3_600_000); }
function calendarDayDistance(rangeStart: Date, value: Date) { return Math.floor((startOfDay(value).getTime() - rangeStart.getTime()) / 86_400_000); }
function timeLabel(date: Date) { return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", hour12: false }).format(date); }
function toInput(date: Date) { const pad = (value: number) => String(value).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
function rangeLabel(days: Date[]) { if (days.length === 1) return new Intl.DateTimeFormat("en-GB", { weekday: "long", month: "long", day: "numeric" }).format(days[0]); return `${new Intl.DateTimeFormat("en-GB", { month: "short", day: "numeric" }).format(days[0])} – ${new Intl.DateTimeFormat("en-GB", { month: "short", day: "numeric" }).format(days.at(-1)!)} `; }
