"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@heroui/react";
import { Pencil, Plus, ReceiptText, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";

const schema = z.object({ name: z.string().trim().min(1, "Service name is required.").max(120), category: z.string().trim().min(1, "Category is required.").max(120), unit: z.enum(["hour", "day", "episode", "fixed"]), rate: z.coerce.number().positive("Rate must be greater than zero."), currency: z.string().trim().length(3, "Use a three-letter currency code.").transform((value) => value.toUpperCase()), notes: z.string().trim().max(2000).optional(), isActive: z.boolean() });
type Values = z.infer<typeof schema>;
type Input = z.input<typeof schema>;
export type ServiceRate = { id: string; name: string; category: string; unit: string; rate: string | number; currency: string; notes: string | null; isActive: boolean };

export function ServiceRateCard({ rates }: { rates: ServiceRate[] }) {
  return <section className="panel overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-[#ebeae6] px-5 py-4 sm:flex-row sm:items-center"><div><h2 className="text-sm font-semibold text-[#343b38]">Service rate card</h2><p className="mt-1 text-xs text-[#858a87]">Your post house’s standard prices for estimating episode budgets.</p></div><RateDialog /></div><div className="divide-y divide-[#efeeea]">{rates.map((rate) => <RateRow key={rate.id} rate={rate} />)}{!rates.length && <div className="px-5 py-12 text-center"><ReceiptText className="mx-auto text-[#a1a7a3]" size={22} /><p className="mt-3 text-sm font-medium text-[#59615d]">No service rates yet</p><p className="mt-1 text-xs text-[#858a87]">Add standard post services to build a consistent estimating baseline.</p></div>}</div></section>;
}

function RateRow({ rate }: { rate: ServiceRate }) { return <div className="flex flex-col justify-between gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold text-[#404844]">{rate.name}</p>{!rate.isActive && <span className="rounded bg-[#f2f1ee] px-1.5 py-0.5 text-[10px] font-semibold text-[#777d79]">Inactive</span>}</div><p className="mt-1.5 text-xs text-[#7d837f]">{rate.category}{rate.notes ? ` · ${rate.notes}` : ""}</p></div><div className="flex items-center gap-3"><p className="text-right text-sm font-semibold text-[#3d4642]">{formatMoney(rate.rate, rate.currency)} <span className="text-xs font-normal text-[#7d837f]">/ {rate.unit}</span></p><RateDialog rate={rate} /></div></div>; }

function RateDialog({ rate }: { rate?: ServiceRate }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const form = useForm<Input, unknown, Values>({ resolver: zodResolver(schema), defaultValues: defaults(rate) });
  function close() { setOpen(false); setError(""); form.reset(defaults(rate)); }
  async function submit(values: Values) { setError(""); const response = await fetch(rate ? `/api/service-rates/${rate.id}` : "/api/service-rates", { method: rate ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, notes: values.notes || null }) }); const body = await response.json().catch(() => null); if (!response.ok) return setError(body?.error ?? "Could not save this service rate."); close(); router.refresh(); }
  return <><Button variant={rate ? "tertiary" : "primary"} onPress={() => setOpen(true)} className={rate ? "min-w-0 border border-[#dfe3df] bg-white text-[#58635e]" : "bg-[#263130] text-white"}>{rate ? <><Pencil size={14} /> Edit</> : <><Plus size={16} /> Add service</>}</Button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#202725]/25 p-4"><div className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-xl border border-[#e2e3de] bg-[#fafbf9] p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold tracking-[-0.03em] text-[#2d3431]">{rate ? "Edit service rate" : "Add service rate"}</h2><p className="mt-1 text-sm text-[#767c78]">Set the current standard price; existing budget lines are not changed.</p></div><Button isIconOnly variant="tertiary" onPress={close} aria-label="Close" className="min-w-0 text-[#7d827e]"><X size={18} /></Button></div><form className="mt-6 space-y-4" onSubmit={form.handleSubmit(submit)}><Field label="Service" error={form.formState.errors.name?.message}><input {...form.register("name")} placeholder="Senior editor" /></Field><Field label="Budget category" error={form.formState.errors.category?.message}><input {...form.register("category")} placeholder="Editorial artists" /></Field><div className="grid gap-3 sm:grid-cols-3"><Field label="Rate" error={form.formState.errors.rate?.message}><input type="number" min="0" step="0.01" {...form.register("rate")} /></Field><Field label="Currency" error={form.formState.errors.currency?.message}><input {...form.register("currency")} placeholder="GBP" /></Field><Field label="Per" error={form.formState.errors.unit?.message}><select {...form.register("unit")}><option value="hour">Hour</option><option value="day">Day</option><option value="episode">Episode</option><option value="fixed">Fixed service</option></select></Field></div><Field label="Notes" error={form.formState.errors.notes?.message}><textarea rows={2} {...form.register("notes")} placeholder="Overtime, equipment, or terms…" /></Field><label className="flex items-center gap-2 text-xs text-[#535b57]"><input type="checkbox" {...form.register("isActive")} /> Available for new estimates</label>{error && <p role="alert" className="text-xs text-[#a35e41]">{error}</p>}<div className="flex justify-end gap-2 border-t border-[#ecebe7] pt-4"><Button type="button" variant="tertiary" onPress={close}>Cancel</Button><Button type="submit" variant="primary" isDisabled={form.formState.isSubmitting} className="bg-[#263130] text-white">{form.formState.isSubmitting ? "Saving…" : "Save service"}</Button></div></form></div></div>}</>;
}

function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-xs font-medium text-[#535b57]">{label}<span className="mt-1.5 block [&_input]:h-10 [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-[#dedfda] [&_input]:px-3 [&_input]:text-sm [&_select]:h-10 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-[#dedfda] [&_select]:bg-white [&_select]:px-2 [&_select]:text-sm [&_textarea]:w-full [&_textarea]:rounded-md [&_textarea]:border [&_textarea]:border-[#dedfda] [&_textarea]:p-3 [&_textarea]:text-sm">{children}</span>{error && <span className="mt-1 block text-[11px] font-normal text-[#a35e41]">{error}</span>}</label>; }
function defaults(rate?: ServiceRate): Input { return { name: rate?.name ?? "", category: rate?.category ?? "", unit: (rate?.unit as Input["unit"]) ?? "day", rate: rate ? Number(rate.rate) : 0, currency: rate?.currency ?? "GBP", notes: rate?.notes ?? "", isActive: rate?.isActive ?? true }; }
function formatMoney(value: string | number, currency: string) { try { return new Intl.NumberFormat("en-GB", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value)); } catch { return `${currency} ${Number(value).toFixed(2)}`; } }
