import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb } from "@/lib/db";
import { episodes } from "@/lib/db/schema";
import { getActiveOrganizationContext } from "@/lib/organizations";
import { canManageEpisodes, isAssignedToEpisode } from "@/lib/permissions";
const schema = z.object({ title: z.string().trim().min(1).max(160), productionCode: z.string().trim().max(40).nullable(), status: z.enum(["development", "assembly", "editor_cut", "review", "locked", "online", "delivered"]), airDate: z.string().nullable(), lockedCutDate: z.string().nullable(), deliveryDeadline: z.string().nullable() });
export async function PATCH(request: Request, { params }: { params: Promise<{ episodeId: string }> }) { if (!(await canManageEpisodes())) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const { episodeId } = await params; if (!(await isAssignedToEpisode(episodeId))) return NextResponse.json({ error: "Episode not found." }, { status: 404 }); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Check the episode details." }, { status: 400 }); const context = await getActiveOrganizationContext(); if (!context?.organization) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const { deliveryDeadline, ...values } = parsed.data; const [episode] = await getDb().update(episodes).set({ ...values, deliveryDeadline: deliveryDeadline ? new Date(deliveryDeadline) : null, updatedAt: new Date() }).where(and(eq(episodes.id, episodeId), eq(episodes.organizationId, context.organization.organizationId))).returning({ id: episodes.id }); return episode ? NextResponse.json(episode) : NextResponse.json({ error: "Episode not found." }, { status: 404 }); }
