import Link from "next/link";
import { ArrowLeft, FileCheck2 } from "lucide-react";
import { notFound } from "next/navigation";

import { ReviewCutActions } from "@/components/review-cut-actions";
import { getActiveOrganizationContext } from "@/lib/organizations";
import { clientCanAccess } from "@/lib/client-access";
import { getCurrentPerson, isExternalReviewerRole } from "@/lib/permissions";
import { getDebugReviewApprovals, withDebugApproval } from "@/lib/debug-review-approvals";
import { isDebugDemoMode } from "@/lib/runtime";
import { getReviewCutWorkspace } from "@/server/data";
import { demoReviewData } from "../page";

export default async function ReviewCutDetailPage({ params }: { params: Promise<{ cutId: string }> }) {
  const { cutId } = await params; const data = await getReviewData(cutId); if (!data) notFound(); const { cut, notes, history } = data;
  return <div className="space-y-5"><Link href="/review" className="flex items-center gap-1 text-xs font-medium text-[#617b75]"><ArrowLeft size={14} /> Approval queue</Link><header className="panel p-6"><div className="flex items-start gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e7ece8] text-[#557169]"><FileCheck2 size={21} /></span><div><p className="text-xs font-medium uppercase tracking-[0.1em] text-[#7a827e]">{cut.showTitle} · E{String(cut.episodeNumber).padStart(2, "0")} {cut.episodeTitle}</p><h1 className="mt-1 text-[27px] font-semibold tracking-[-0.045em] text-[#262c29]">{cut.title}</h1><p className="mt-1 text-sm text-[#777d79]">Version {cut.version} · {cut.approvalStatus.replaceAll("_", " ")} · Approval due {dateLabel(cut.dueAt)}</p></div></div></header><section className="grid gap-4 xl:grid-cols-[1.3fr_0.7fr]"><ReviewCutActions cutId={cut.id} notes={notes} initialApprovalStatus={cut.approvalStatus} /><aside className="panel p-5"><h2 className="text-sm font-semibold text-[#343b38]">Version history</h2><div className="mt-4 space-y-3">{history.map((item) => <div key={item.id} className={`rounded-lg border p-3 ${item.id === cut.id ? "border-[#b8cec5] bg-[#f2f8f5]" : "border-[#ecebe7]"}`}><p className="text-sm font-semibold text-[#414945]">v{item.version} · {item.title}</p><p className="mt-1 text-xs capitalize text-[#818783]">{item.status.replaceAll("_", " ")} · {item.approvalStatus.replaceAll("_", " ")}</p></div>)}</div></aside></section></div>;
}
function dateLabel(value: Date | null) { return value ? new Intl.DateTimeFormat("en-GB", { month: "short", day: "numeric" }).format(value) : "—"; }
async function getReviewData(cutId: string) { if (isDebugDemoMode) { const demo = demoReviewData(); const approvals = await getDebugReviewApprovals(); const cut = demo.cuts.map((item) => withDebugApproval(item, approvals)).find((item) => item.id === cutId); if (!cut) return null; return { cut, notes: [{ id: "demo-note-1", body: "Hold two beats longer on the exterior before cutting inside.", authorName: "Mara Voss, Director", department: "Editorial", priority: "high", timecodeSeconds: "1102.500", status: "open" }, { id: "demo-note-2", body: "Use the alternate opening title card supplied in the delivery folder.", authorName: "Northstar Network", department: "Delivery", priority: "normal", timecodeSeconds: "8.000", status: "addressed" }], history: demo.cuts.filter((item) => item.episodeId === cut.episodeId).map((item) => withDebugApproval(item, approvals)) }; } const context = await getActiveOrganizationContext(); if (!context?.organization) return null; const workspace = await getReviewCutWorkspace(context.organization.organizationId, cutId); if (!workspace) return null; const person = await getCurrentPerson(); if (isExternalReviewerRole(person?.role) && !(await clientCanAccess({ organizationId: context.organization.organizationId, userId: context.userId, showId: workspace.cut.showId, episodeId: workspace.cut.episodeId, reviewCutId: cutId }))) return null; return workspace; }
